name: "SkyLab"
main: "at.Grevinelveck.SkyLab.SkyLab"
version: "1.0"


commands:
   basic:SkyLab
      description: This command brings the power of your orbital death ray onto an annoyance.
      usage: /SkyLab [player]
      permission: SkyLab.Deathray
      permission-message: You don't have <permission>